apiVersion: v1
kind: ConfigMap
metadata:
  name: homebridge-config-template
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "bridge": {
        "name": "Homebridge",
        "username": "CE:B5:A7:D9:F2:3C",
        "port": 51826,
        "pin": "031-45-154",
        "advertiser": "ciao"
      },
      "accessories": [],
      "platforms": [
        {
          "platform": "HomeAssistant",
          "name": "Home Assistant",
          "host": "http://home-assistant.home-assistant.svc.cluster.local",
          "token": "__HA_TOKEN__",
          "filter_by_domains": ["alarm_control_panel"],
          "filter_by_entities": [
            "light.emilies_lamp",
            "light.bens_lamp",
            "sensor.hub_2_tempsensor_temperature",
            "sensor.hub_2_humisensor_humidity",
            "sensor.co2",
            "sensor.pm2_5",
            "binary_sensor.back_door",
            "binary_sensor.front_door",
            "binary_sensor.window",
            "binary_sensor.back_window",
            "binary_sensor.bathroom_window",
            "binary_sensor.front_window",
            "binary_sensor.front_window_2",
            "binary_sensor.left_window",
            "binary_sensor.right_window",
            "binary_sensor.side_window",
            "binary_sensor.left_double_window",
            "binary_sensor.left_fireplace_window",
            "binary_sensor.right_double_window",
            "binary_sensor.right_fireplace_window",
            "vacuum.upstairs_vacuum"
          ]
        }
      ]
    }
