apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: homebridge
  ports:
    - name: http
      port: 8581
      targetPort: 8581
      protocol: TCP
