{{- if .Values.dashboard.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: {{ .namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.homelab`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
{{- end }}
