{{- if .Values.dashboard.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  ingressClassName: traefik
  rules:
    - host: traefik.homelab
      http:
        paths:
          - backend:
              service:
                name: traefik
                port:
                  number: 80
            path: /
            pathType: Prefix
{{- end }}
