{{- if .Values.tailscale.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-tailscale
  annotations:
    tailscale.com/hostname: "{{ .Values.tailscale.hostname }}"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  ports:
    - name: http
      port: 80
      targetPort: 8080
{{- end }}
