namespace: reloader

reloader:
  reloader:
    watchGlobally: true
    autoReloadAll: false
    logFormat: json
    deployment:
      resources:
        requests:
          memory: 24Mi
          cpu: 10m
        limits:
          memory: 64Mi
