apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/bafulton/homelab
        revision: main
        files:
          - path: kubernetes/apps/*/values.yaml
  template:
    metadata:
      name: '{{ get . "name" | default .path.basenameNormalized }}'  # eg, "plex" from "kubernetes/apps/plex"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ get . "syncWave" | default 0 }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bafulton/homelab
        targetRevision: main
        path: '{{ .path.path }}'  # eg, kubernetes/apps/plex
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ get . "namespace" | default .path.basenameNormalized }}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          {{- if (get . "serverSideApply" | default false) }}
          - ServerSideApply=true
          {{- end }}
