namespace: monitoring
syncWave: "0"
serverSideApply: true  # large CRDs; hits size limit on client-side apply

kube-prometheus-stack:
  # A complete list of values can be found here:
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

  defaultRules:
    create: false

  alertmanager:
    enabled: false

  grafana:
    enabled: false
    ingress:
      enabled: false
      # ingressClassName: tailscale
      # hosts:
      #   - grafana
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi

  prometheus:
    prometheusSpec:
      retention: 3d
      scrapeInterval: 30s
      evaluationInterval: 30s
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:

          memory: 512Mi
    # ingress:
    #   enabled: true
    #   ingressClassName: tailscale
    #   hosts:
    #     - prometheus

  prometheusOperator:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 100Mi

  kube-state-metrics:
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
      limits:
        memory: 100Mi

  prometheus-node-exporter:
    extraArgs:
      - --collector.thermal_zone
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi

  kubeControllerManager:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false
