syncWave: "0"
serverSideApply: true

kube-prometheus-stack:
  # A complete list of values can be found here:
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

  defaultRules:
    create: false

  alertmanager:
    enabled: false

  # grafana:
  #   ingress:
  #     enabled: true
  #     ingressClassName: tailscale
  #     hosts:
  #       - grafana

  kubeEtcd:
    # todo: enable (see comments in values file)
    enabled: false

  kubeScheduler:
    # todo: enable (see comments in values file)
    enabled: false

  kubeProxy:
    # todo: enable (see comments in values file)
    enabled: false
